// <auto-generated />
using ESG.ESGDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ESG.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ESG.Models.ESGmodel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FtseESG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssESG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MsciESG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Refi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SapESG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SusESG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwCompanyRank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ESGs");
                });
#pragma warning restore 612, 618
        }
    }
}
